2025-07-29 21:28:01,474 - __main__ - ERROR - Initialization failed: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
Traceback (most recent call last):
  File "G:\project\life_insurence_query\src\query.py", line 40, in __init__
    self.nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mothi\AppData\Local\Programs\Python\Python313\Lib\site-packages\spacy\__init__.py", line 52, in load
    return util.load_model(
           ~~~~~~~~~~~~~~~^
        name,
        ^^^^^
    ...<4 lines>...
        config=config,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\mothi\AppData\Local\Programs\Python\Python313\Lib\site-packages\spacy\util.py", line 484, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
2025-07-29 21:29:40,532 - vectordb - INFO - Loaded embedding cache with 1080 entries
2025-07-29 21:29:40,540 - faiss.loader - INFO - Loading faiss with AVX512 support.
2025-07-29 21:29:40,541 - faiss.loader - INFO - Could not load library with AVX512 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx512'")
2025-07-29 21:29:40,541 - faiss.loader - INFO - Loading faiss with AVX2 support.
2025-07-29 21:29:40,583 - faiss.loader - INFO - Successfully loaded faiss with AVX2 support.
2025-07-29 21:29:40,591 - faiss - INFO - Failed to load GPU Faiss: name 'GpuIndexIVFFlat' is not defined. Will not load constructor refs for GPU indexes. This is only an error if you're trying to use GPU Faiss.
2025-07-29 21:29:40,633 - vectordb - INFO - Database loaded from insurance_vector_db
2025-07-29 21:31:45,728 - __main__ - ERROR - PDF extraction failed: 404 Client Error: Not Found for url: https://example.com/policy.pdf
